### ISSUE TITLE
《使用Hugo搭建Blog》勘误

### ISSUE THREAD

**Issue by CyrusYip** [PILIHU2022/PILIHU2022.github.io#2]
https://github.com/PILIHU2022/PILIHU2022.github.io/blob/6f117440458eba19dc091a573177c27f814dc4d9/content/posts/Hugo-Blog.md?plain=1#L92

Cloudflare Pages 可以设置 Hugo 版本，参看 <https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site/#use-a-specific-or-newer-hugo-version> 。

**Comment by PILIHU2022** [comment]
> https://github.com/PILIHU2022/PILIHU2022.github.io/blob/6f117440458eba19dc091a573177c27f814dc4d9/content/posts/Hugo-Blog.md?plain=1#L92
> 
> Cloudflare Pages 可以设置 Hugo 版本，参看 https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site/#use-a-specific-or-newer-hugo-version 。
非常感谢！我尝试了很久都没搞定这个，原来可以这样
